platform :ios, '15.1'
use_frameworks! :linkage => :static  # ⬅️ replace use_modular_headers!

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})',
  __dir__]).strip

prepare_react_native_project!

target 'piarcha_react' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  # Only these two need modular headers:
  pod 'GoogleMaps', :modular_headers => true
  pod 'Google-Maps-iOS-Utils', :modular_headers => true

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)
    installer.pods_project.targets.each do |t|
      t.build_configurations.each { |c| c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1' }
    end
  end
end
